version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    container_name: hono-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=file:./dev.db
    volumes:
      - backend_data:/app/prisma
    networks:
      - app-network
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    container_name: react-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  backend_data:
    driver: local

networks:
  app-network:
    driver: bridge
